---
- setup:
    filter: "{{ item }}"
  loop:
    - 'ansible_distribution*'
    - 'ansible_hostname'
  tags:
    - always

## Check reboot flag in /opt/Tanium/TaniumClient/Tools/CustomTags.txt
- name: Check Reboot Flag
  shell: "grep -E 'TRUE|FALSE' "{{ custom_flag_path }}""
  register: autoreboot
  failed_when: "{{ custom_flag_failed_when }}"
  ignore_errors: true
  tags:
    - always

## Print hosts who have autoreboot set to false
- name: Print VMs with autoreboot set to false
  when: "{{ custom_flag_when }"
  debug: msg="{{ custom_flag_print_out }}""
  tags:
    - always

## Run yum update. This updates everything on a system
- name: Update Server
  register: yum_update_out
  async: "{{ yum_update_async }}"
  poll: "{{ yum_update_poll }}"
  yum:
    name: "*"
    state: latest
  when: "{{ yum_update_when }}"
  tags: [ never, update ]

## Check if RHEL6 VMs need a reboot after update
- name: Check if reboot is needed on RHEL6 servers
  shell: "{{ chk_reboot_rhel6_svc }}"
  register: reboot_needed6
  ignore_errors: true
  changed_when: false
  failed_when: "{{ chk_reboot_rhel6_failed_when }}"
  when: "{{ chk_reboot_rhel6_when }}"
  tags: [ never, update ]

## Check if RHEL7/8/9 VMs need a reboot after update
- name: Check if reboot is needed RHEL7+
  shell: "{{ chk_reboot_rhel7_svc }}"
  register: reboot_needed
  ignore_errors: true
  changed_when: false
  failed_when: "{{ chk_reboot_rhel7_failed_when }}"
  when: "{{ chk_reboot_rhel7_when }}"
  tags: [ never, update ]

## Reboot RHEL6 VMs
- name: Reboot RHEL6 VMs
  reboot:
    msg: "{{ console_reboot_msg }}"
    pre_reboot_delay: "{{ server_reboot_pre_delay }}"
    post_reboot_delay: "{{ server_reboot_post_delay }}"
    reboot_timeout: "{{ server_reboot_timeout }}"
    test_command: "{{ server_reboot_test_cmd }}"
  ignore_errors: true
  when: "{{ server_reboot_when_rhel6 }}"
  tags: [ never, update ]

## Reboot RHEL7+ VMs
- name: Reboot RHEL7+ VMs
  reboot:
    msg: "{{ console_reboot_msg }}"
    pre_reboot_delay: "{{ server_reboot_pre_delay }}"
    post_reboot_delay: "{{ server_reboot_post_delay }}"
    reboot_timeout: "{{ server_reboot_timeout }}"
    test_command: "{{ server_reboot_test_cmd }}"
  ignore_errors: true
  when: "{{ server_reboot_when_rhel7 "}}
  tags: [ never, update ]


