---
    - name: Create {{ inventory_main_nonprod }} file
      tags: nonprod
      copy:
        dest: "{{ inventory_out_nonprod }}"
        content: |
          [excludes]
          [{{ dlt_day7 }}]
          [{{ dlt_day8 }}]
          [{{ dlt_day9 }}]
          [{{ dlt_day10 }}]
          [{{ dlt_day11 }}]
          [{{ dlt_day12 }}]
          [{{ qa_day7 }}]
          [{{ qa_day8 }}]
          [{{ qa_day9 }}]
          [{{ qa_day10 }}]
          [{{ qa_day11 }}]
          [{{ qa_day12 }}]

    - name: Create new Prod inventory file
      tags: prod
      copy:
        dest: "{{ inventory_out_prod }}"
        content: |
          [excludes]
          [{{ prod_day7 }}]
          [{{ prod_day8 }}]
          [{{ prod_day9 }}]
          [{{ prod_day10 }}]
          [{{ prod_day11 }}]
          [{{ prod_day12 }}]
          [{{ dr_day7 }}]
          [{{ dr_day8 }}]
          [{{ dr_day9 }}]
          [{{ dr_day10 }}]
          [{{ dr_day11 }}]
          [{{ dr_day12 }}]
