---
- hosts: localhost
  gather_facts: false
  vars:
    inventory_out_nonprod: /etc/ansible/inventory/Quarterly-NonProd
    inventory_src: /root/inventory-src/
  tasks:
    - name: gather Excludes
      ansible.builtin.slurp:
        src: "{{ inventory_src }}excludes_hostlist.txt"
      register: excludes_hosts

    - name: print out variable
      ansible.builtin.debug:
        msg: "{{ excludes_hosts }}"

    - name: gather  DLT 7
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt07_hostlist.txt"
      register: dlt07_hosts
        
    - name: gather DLT 8
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt08_hostlist.txt"
      register: dlt08_hosts
        
    - name: gather DLT 9
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt09_hostlist.txt"
      register: dlt09_hosts

    - name: gather DLT 10
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt10_hostlist.txt"
      register: dlt10_hosts

    - name: gather DLT 11
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt11_hostlist.txt"
      register: dlt11_hosts

    - name: gather DLT 12
      ansible.builtin.slurp:
        src: "{{ inventory_src }}dlt12_hostlist.txt"
      register: dlt12_hosts
           
    - name: Create new inventory file
      copy:
        dest: "{{ inventory_out_nonprod }}"
        content: |
          [excludes]
          [dlt7]
          [dlt8]
          [dlt9]
          [dlt10]
          [dlt11]
          [dlt12]
          [qa7]
          [qa8]
          [qa9]
          [qa10]
          [qa11]
          [qa12]

    - name: write Excludes
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ excludes_hosts.content|b64decode }}"
        insertafter: '^\[excludes\]'
        state: present

    - name: write DLT 7
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt07_hosts.content|b64decode }}"
        insertafter: '^\[dlt7\]'
        state: present

    - name: write DLT 8
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt08_hosts.content|b64decode }}"
        insertafter: '^\[dlt8\]'
        state: present

    - name: write DLT 9
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt09_hosts.content|b64decode }}"
        insertafter: '^\[dlt9\]'
        state: present

    - name: write DLT 10
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt10_hosts.content|b64decode }}"
        insertafter: '^\[dlt10\]'
        state: present

    - name: write DLT 11
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt11_hosts.content|b64decode }}"
        insertafter: '^\[dlt11\]'
        state: present

    - name: write DLT 12
      lineinfile:
        path: "{{ inventory_out_nonprod }}"
        line: "{{ dlt12_hosts.content|b64decode }}"
        insertafter: '^\[dlt12\]'
        state: present
