---
    - name: Create {{ inventory_main_nonprod }} file
      copy:
        dest: "{{ inventory_out_nonprod }}"
        content: |
          [excludes]
          [{{ dlt_day7 }}]
          [{{ dlt_day8 }}]
          [{{ dlt_day9 }}]
          [{{ dlt_day10 }}]
          [{{ dlt_day11 }}]
          [{{ dlt_day12 }}]
          [{{ qa_day7 }}]
          [{{ qa_day8 }}]
          [{{ qa_day9 }}]
          [{{ qa_day10 }}]
          [{{ qa_day11 }}]
          [{{ qa_day12 }}]
